### ISSUE TITLE
ENOENT: no such file or directory, open 'C:\style.css

### ISSUE THREAD

**Issue by Nantris** [JamesKyburz/dialogs#28]
I tried require and import, but always get: 

`fs.js:640 Uncaught Error: ENOENT: no such file or directory, open 'C:\style.css'`

**Comment by JamesKyburz** [comment]
Are you using browserify?

**Comment by Nantris** [comment]
I'm not sure. I'm using the electron-react-boilerplate. It may be used. I know I'm using webpack at the least.

I moved on from this solution for now. Thank you for taking the time to respond.

**Comment by JamesKyburz** [comment]
This module uses `brfs` which is a `browserify` transform to inline the css.

If you are using `webpack` then `brfs` needs to be configured.

I think if you add a loader for `brfs` as described in https://github.com/webpack/transform-loader it should work.
