### ISSUE TITLE
[Question] Basic usage on Web/Electron app

### ISSUE THREAD

**Issue by jorgerobles** [JamesKyburz/dialogs#35]
Hi
I've got an app that serves on web and on an electron app.
Since web browser has no requires I've made a polyfill to use the native ones, but expected on electron version to work plainly. 
I've got a `cannot find module dialogs` error on DevTools.

What's the way to go? Thanks.

**Comment by JamesKyburz** [comment]
Have you installed dialogs prior to running the app? Using either npm or yarn.

**Comment by jorgerobles** [comment]
Yes, of course. Sorry, I forgot I opened this issue. It's solved, thanks!

**Comment by JamesKyburz** [comment]
OK. Great!
