### ISSUE TITLE
Uninitialized Memory Exposure

### ISSUE THREAD

**Issue by hubdotcom** [JamesKyburz/dialogs#41]
Uninitialized Memory Exposure

Medium severity
Vulnerable module: concat-stream

Introduced through: dialogs@1.1.19 › brfs@1.4.3 › static-module@1.3.1 › concat-stream@1.4.10

https://snyk.io/vuln/npm:concat-stream:20160901

**Comment by JamesKyburz** [comment]
Fixed in 2.0.1
