### ISSUE TITLE
TypeError: dialogs.prompt is not a function

### ISSUE THREAD

**Issue by nisdas** [JamesKyburz/dialogs#46]
None of the functions from the dialogs module are able to be accessed. They are all stated as non existent

**Comment by JamesKyburz** [comment]
Are you calling dialogs as a function like so `var dialogs = require('dialogs')()`

**Comment by JamesKyburz** [comment]
[example code](http://requirebin.com/?gist=5b6d6b63f8709deb3b5a)

**Comment by nisdas** [comment]
I tried doing that ,but then I got 

`ReferenceError: window is not defined`

so then I decided to change 
`var dialogs = require('dialogs')()` 
to
`let dialogs;`
`if (typeof window !== 'undefined' && typeof document !== 'undefined') {
   dialogs = require('dialogs')().default;
}`

Then I get another error which is 
`TypeError: Cannot read property 'alert' of undefined`

**Comment by JamesKyburz** [comment]
This module only works in the context of a browser. Currently it only supports using [browserify](https://www.npmjs.com/package/browserify)

**Comment by nisdas** [comment]
ahh ok thanks, sorry should have read  the documentation more closely.

**Comment by JamesKyburz** [comment]
np
