### ISSUE TITLE
TypeError: dialogs.alert is not a function

### ISSUE THREAD

**Issue by akkravikumar** [JamesKyburz/dialogs#48]
Im getting TypeError: dialogs.alert is not a function when need to show an alert. Im using electron.

**Comment by kounelios13** [comment]
Try this(Using electron too)
```
var Dialog = require('dialogs')
var dialogs = Dialog();
dialogs.alert()
```

**Comment by Vaelek** [comment]
Ran into the same issue and that solved it thanks. I just simplified to

`const dialogs = require('dialogs')()`

**Comment by Vaelek** [comment]
How is this closed? It was first reported **a year ago**.. And in that time there was not a single comment from the dev, and it has now been closed **without** even bothering to update the readme to reflect the proper usage. I would do it myself and submit a PR, but as I can see there is one hanging out from 2018 as well that seems futile. If you don't intend to fix the issue, at least leave this open for others to see.

**Comment by JamesKyburz** [comment]
@Vaelek The reason I closed this issue was because you + 1 showed example code how to call `Dialogs()`. Maybe the `readme` wasn't clear enough so I updated the example code.
